url: ""
baseurl: ""
title: "Chair of Software Engineering"
description: >-
  Website of the Chair of Software Engineering
  at Constructor Institute of Technology.
  Latest news about our research and projects.

cicse:
  bar_link: false
  nav_links:
    - link: 'people'
      title: People

collections:
  people:
    output: true
    sort_by: title
    order:
      - index.md

theme: jekyll-theme-cicse

liquid:
  error_mode: strict
  strict_filters: true

postcss:
  cache: false

exclude:
  - jekyll-theme-cicse
  - README.md
  - postcss.config.js
  - package.json
  - yarn.lock
  - tailwind.config.js
  - LICENSE
